import type { SchemaSnapshot, SchemaDiff } from '../db/types';

export function generateSQL(diff: SchemaDiff, after: SchemaSnapshot): string {
  const lines = [`-- DB Diagram Migration — ${new Date().toISOString()}`, ''];

  for (const name of diff.removedRelationships) {
    const rel = after.relationships.find(r => r.constraintName === name);
    if (rel) lines.push(`ALTER TABLE \`${rel.fromTable}\` DROP FOREIGN KEY \`${name}\`;`);
  }
  for (const name of diff.removedTables) lines.push(`DROP TABLE IF EXISTS \`${name}\`;`);

  for (const name of diff.addedTables) {
    const tbl = after.tables.find(t => t.name === name);
    if (!tbl) continue;
    const cols = tbl.columns.map(c => {
      const parts = [`  \`${c.name}\` ${c.type}`];
      if (c.isAutoIncrement) parts.push('AUTO_INCREMENT');
      parts.push(c.nullable ? 'NULL' : 'NOT NULL');
      if (c.defaultValue !== null) parts.push(`DEFAULT '${c.defaultValue}'`);
      if (c.comment) parts.push(`COMMENT '${c.comment}'`);
      return parts.join(' ');
    });
    const pks = tbl.columns.filter(c => c.isPrimaryKey).map(c => `\`${c.name}\``);
    if (pks.length) cols.push(`  PRIMARY KEY (${pks.join(', ')})`);
    const npIdx = tbl.indexes.filter(i => !i.primary);
    for (const idx of npIdx) cols.push(`  ${idx.unique ? 'UNIQUE ' : ''}KEY \`${idx.name}\` (${idx.columns.map(c => `\`${c}\``).join(', ')})`);
    lines.push('', `CREATE TABLE \`${tbl.name}\` (\n${cols.join(',\n')}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`, '');
  }

  for (const mod of diff.modifiedTables) {
    const tbl = after.tables.find(t => t.name === mod.name);
    if (!tbl) continue;
    for (const col of mod.removedColumns) lines.push(`ALTER TABLE \`${mod.name}\` DROP COLUMN \`${col}\`;`);
    for (const colName of mod.addedColumns) {
      const col = tbl.columns.find(c => c.name === colName);
      if (!col) continue;
      lines.push(`ALTER TABLE \`${mod.name}\` ADD COLUMN \`${col.name}\` ${col.type} ${col.nullable ? 'NULL' : 'NOT NULL'};`);
    }
    for (const idxName of mod.removedIndexes) lines.push(`DROP INDEX \`${idxName}\` ON \`${mod.name}\`;`);
    for (const idxName of mod.addedIndexes) {
      const idx = tbl.indexes.find(i => i.name === idxName);
      if (!idx || idx.primary) continue;
      lines.push(`CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX \`${idx.name}\` ON \`${mod.name}\` (${idx.columns.map(c => `\`${c}\``).join(', ')});`);
    }
  }

  for (const name of diff.addedRelationships) {
    const rel = after.relationships.find(r => r.constraintName === name);
    if (!rel) continue;
    lines.push(`ALTER TABLE \`${rel.fromTable}\` ADD CONSTRAINT \`${rel.constraintName}\` FOREIGN KEY (\`${rel.fromColumn}\`) REFERENCES \`${rel.toTable}\`(\`${rel.toColumn}\`) ON DELETE ${rel.onDelete} ON UPDATE ${rel.onUpdate};`);
  }

  return lines.join('\n');
}

function toPascal(s: string): string { return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase()).replace(/^[a-z]/, c => c.toUpperCase()); }
function toCamel(s: string): string { const p = toPascal(s); return p[0].toLowerCase() + p.slice(1); }
function mysqlToPrisma(t: string, ai: boolean): string {
  if (ai) return 'Int';
  const l = t.toLowerCase();
  if (/bigint/.test(l)) return 'BigInt';
  if (/int/.test(l)) return 'Int';
  if (/float|double|decimal/.test(l)) return 'Decimal';
  if (/bool|tinyint\(1\)/.test(l)) return 'Boolean';
  if (/datetime|timestamp/.test(l)) return 'DateTime';
  if (/json/.test(l)) return 'Json';
  return 'String';
}
function mysqlToTS(t: string): string {
  const l = t.toLowerCase();
  if (/int/.test(l)) return 'number';
  if (/float|double|decimal/.test(l)) return 'number';
  if (/bool|tinyint\(1\)/.test(l)) return 'boolean';
  if (/datetime|timestamp|date/.test(l)) return 'Date';
  if (/json/.test(l)) return 'object';
  return 'string';
}

export function generatePrisma(schema: SchemaSnapshot): string {
  const lines = [`// Prisma schema — generated by DB Diagram`, `// ${new Date().toISOString()}`, '',
    'datasource db {', '  provider = "mysql"', '  url      = env("DATABASE_URL")', '}', '',
    'generator client {', '  provider = "prisma-client-js"', '}', ''];

  for (const tbl of schema.tables) {
    const fks = schema.relationships.filter(r => r.fromTable === tbl.name);
    const refs = schema.relationships.filter(r => r.toTable === tbl.name);
    lines.push(`model ${toPascal(tbl.name)} {`);
    for (const col of tbl.columns) {
      const pt = mysqlToPrisma(col.type, col.isAutoIncrement);
      const opt = col.nullable ? '?' : '';
      const attrs: string[] = [];
      if (col.isPrimaryKey) attrs.push('@id');
      if (col.isAutoIncrement) attrs.push('@default(autoincrement())');
      else if (col.defaultValue === 'CURRENT_TIMESTAMP') attrs.push('@default(now())');
      if (col.isUnique && !col.isPrimaryKey) attrs.push('@unique');
      lines.push(`  ${col.name.padEnd(22)} ${pt}${opt}  ${attrs.join(' ')}`.trimEnd());
    }
    for (const fk of fks) lines.push(`  ${toCamel(fk.toTable).padEnd(22)} ${toPascal(fk.toTable)}  @relation("${fk.constraintName}", fields: [${fk.fromColumn}], references: [${fk.toColumn}])`);
    for (const ref of refs) lines.push(`  ${(toCamel(ref.fromTable)+'s').padEnd(22)} ${toPascal(ref.fromTable)}[]`);
    const npIdx = tbl.indexes.filter(i => !i.primary && i.columns.length > 1);
    for (const idx of npIdx) lines.push(`  @@${idx.unique ? 'unique' : 'index'}([${idx.columns.join(', ')}])`);
    lines.push('}', '');
  }
  return lines.join('\n');
}

export function generateTypeORM(schema: SchemaSnapshot): string {
  const lines = [`// TypeORM Entities — generated by DB Diagram`, `// ${new Date().toISOString()}`, '',
    "import { Entity, Column, PrimaryGeneratedColumn, Index, ManyToOne, OneToMany, JoinColumn } from 'typeorm';", ''];

  for (const tbl of schema.tables) {
    const fks = schema.relationships.filter(r => r.fromTable === tbl.name);
    const refs = schema.relationships.filter(r => r.toTable === tbl.name);
    const npIdx = tbl.indexes.filter(i => !i.primary);
    for (const idx of npIdx) lines.push(`@Index([${idx.columns.map(c => `'${c}'`).join(', ')}]${idx.unique ? ', {unique:true}' : ''})`);
    lines.push(`@Entity('${tbl.name}')`);
    lines.push(`export class ${toPascal(tbl.name)} {`);
    for (const col of tbl.columns) {
      if (col.isPrimaryKey && col.isAutoIncrement) lines.push(`  @PrimaryGeneratedColumn()`);
      else if (col.isPrimaryKey) lines.push(`  @PrimaryGeneratedColumn('uuid')`);
      else {
        const opts: string[] = [];
        if (col.nullable) opts.push('nullable: true');
        if (col.isUnique) opts.push('unique: true');
        if (col.comment) opts.push(`comment: '${col.comment}'`);
        lines.push(`  @Column(${opts.length ? `{ ${opts.join(', ')} }` : ''})`);
      }
      lines.push(`  ${col.name}: ${mysqlToTS(col.type)};`, '');
    }
    for (const fk of fks) { lines.push(`  @ManyToOne(() => ${toPascal(fk.toTable)})`); lines.push(`  @JoinColumn({ name: '${fk.fromColumn}' })`); lines.push(`  ${toCamel(fk.toTable)}: ${toPascal(fk.toTable)};`, ''); }
    for (const ref of refs) { lines.push(`  @OneToMany(() => ${toPascal(ref.fromTable)}, e => e.${toCamel(tbl.name)})`); lines.push(`  ${toCamel(ref.fromTable)}s: ${toPascal(ref.fromTable)}[];`, ''); }
    lines.push('}', '');
  }
  return lines.join('\n');
}
